### ISSUE TITLE
Need help for local deployment!

### ISSUE THREAD

**Issue by BIOBRICK** [JoshuaChou2018/AutoBA#1]
Amazing work, tks for providing such useful tool!
Yet I don't quite understand how to deploy the tool locally. Especially when I download the codellam model. There are few problems:
1. Any difference between these model?
2. Is this tool compatible with latest codellam2 models ?
3. What is the "URL from email"? I'm not really proficient at LLM models, can we get some examples or can you provide some related info about how to get this URL?
4. Possibility to train or fine-tune to get a novel model in specific domain? For example, a metagenomics analysis machine for my own purpose by fine-tune the model?
Wish to get some answers. Again, tks for develop such amazing tool !

**Comment by JoshuaChou2018** [comment]
Hi, thank you for your message!
1. The difference between local models is that the model size is different, meaning that the bigger the model you need the bigger the GPU, and the results may be better. But for now, we recommend using chatgpt4 as the backend. Our codellama backend is only used in development for the moment.
2. The codellama backends we offer are llama 2.
3. You should apply them at META and will get an email with the link.
4. Yes, we are currently working on that. Will publish it soon.
