### ISSUE TITLE
litellm support?

### ISSUE THREAD

**Issue by antonkulaga** [JoshuaChou2018/AutoBA#11]
So far, https://www.litellm.ai/ makes all models support openai api, that means that there is not need to support separate codebases for llamas and other opensource models and that current openai implementation can be switched with minimal code changes to support more models via litellm. I am actively using litellm in my projects, so if you think it is worth doing can probably allocate time to add its support

**Comment by JoshuaChou2018** [comment]
this is a good suggestion for online llms, will support this for the next build

**Comment by JoshuaChou2018** [comment]
Feature is included in dev-v1.x.x
