### ISSUE TITLE
invalid response

### ISSUE THREAD

**Issue by wangnuo-log** [JoshuaChou2018/AutoBA#13]
[test.txt](https://github.com/user-attachments/files/17712400/test.txt)
您好，我使用 conda 配置了您对应的环境，并修改了software_database 软件配置的mamba改为conda，但是我在使用
```
python app.py --config ./examples/case1.1/config.yaml --model codellama-7bi
```
的时候，会出现无效的回复并不断循环的时候，请问这个是我这边模型不行导致的一个问题还是说，其他的调整导致的问题

**Comment by JoshuaChou2018** [comment]
Hi, invalid response是因为llm返回的结果不符合json格式，codellama-7bi模型性能比较差，建议使用34bi（可以使用ollama一键部署），或者使用GPT-4 API（目前测试效果最好）

**Comment by wangnuo-log** [comment]
> Hi, invalid response是因为llm返回的结果不符合json格式，codellama-7bi模型性能比较差，建议使用34bi（可以使用ollama一键部署），或者使用GPT-4 API（目前测试效果最好）

很感谢您的回复，我改用codellama:34b的时候确实是可以正常运行，并输出对应的结果

但是我在使用参数
```
python app.py --config ./examples/case1.1/config.yaml --model ollama_codellama:34b --execute True
```
的时候出现一些问题，我这里使用的是case1.1，然后调用了脚本
```
bash -i -e ./examples/case1.1/output/1.sh.execute.sh
```
脚本内容如下：
```
mamba activate abc_runtime
STAR --runMode alignReads --genomeDir /path/to/mouse_genome --readFilesIn ./examples/case1.1/data/SRR1374921.fastq.gz --outFileNamePrefix ./examples/case1.1/output/LoGlu_rep1_ --outSAMtype BAM SortedByCoordinate --limitBAMsortRAM 10000000000 --outWigType wiggle --outWigStrand Unstranded --twopassMode Basic --outFilterMismatchNmax 999 --outFilterMatchNmin 16
```
脚本似乎没有正确使用提供的参考，遇到以下报错
```
        STAR version: 2.7.11b   compiled: 2024-07-03T14:39:20+0000 :/opt/conda/conda-bld/star_1720017372352/work/source
Nov 19 12:16:15 ..... started STAR run
Nov 19 12:16:15 ..... loading genome

EXITING because of FATAL ERROR: could not open genome file /path/to/mouse_genome//genomeParameters.txt
SOLUTION: check that the path to genome files, specified in --genomeDir is correct and the files are present, and have user read permsissions

Nov 19 12:16:15 ...... FATAL ERROR, exiting
```
之后脚本就暂停并不再继续将报错提供给app.py脚本，脚本暂停，请问这个问题您那边是否遇到，需要如何解决呢？

**Comment by JoshuaChou2018** [comment]
STAR是已知问题软件，开源llm会生成bug代码，所以我们在blacklist里面加入了STAR，建议换成其他mapping软件。API llm一般可以正确生成STAR代码，生产环境建议使用GPT-4 API。

**Comment by wangnuo-log** [comment]
> STAR是已知问题软件，开源llm会生成bug代码，所以我们在blacklist里面加入了STAR，建议换成其他mapping软件。API llm一般可以正确生成STAR代码，生产环境建议使用GPT-4 API。

很感谢您的回复，我这边查看您这边app.py的代码，确实是添加了blacklist，但是似乎在生成response的时候，仍然会有STAR的回复并执行。
您那边是否有些开源的LLM推荐，或者在分析时候的config.yaml指定使用的mapping软件呢？
由于我们考虑离线使用LLM，所以暂时是不考虑API形式的LLM使用的。

**Comment by JoshuaChou2018** [comment]
开源llm可以试试deepseek coder instruct，如果开源llm有时不识别blacklist，可以把相关要求添加在goal里即可

**Comment by wangnuo-log** [comment]
我这边也按照您的推荐，在hugging face上下载了deepseek-coder-33b-instruct，但是在运行的时候似乎出现没有办法正常运行
```
CUDA_VISIBLE_DEVICES=1 python app.py --config ./examples/case1.1/config.yaml --model deepseek-coder-33b-instruct
```
报错问题为：
```
{'data_list': ['./examples/case1.1/data/SRR1374921.fastq.gz: single-end mouse rna-seq reads, replicate 1 in LoGlu group', './examples/case1.1/data/SRR1374922.fastq.gz: single-end mouse rna-seq reads, replicate 2 in LoGlu group', './examples/case1.1/data/SRR1374923.fastq.gz: single-end mouse rna-seq reads, replicate 1 in HiGlu group', './examples/case1.1/data/SRR1374924.fastq.gz: single-end mouse rna-seq reads, replicate 2 in HiGlu group', './examples/case1.1/data/TruSeq3-SE.fa: trimming adapter', './examples/case1.1/data/mm39.fa: mouse mm39 genome fasta', './examples/case1.1/data/mm39.ncbiRefSeq.gtf: mouse mm39 genome annotation'], 'output_dir': './examples/case1.1/output', 'goal_description': 'find the differentially expressed genes', 'meta': {'info': 'meta-data recorded by users for reference only', 'title': 'The transcriptional landscape of mouse beta cells compared to human beta cells reveals notable species differences in long non-coding RNA and protein-coding gene expression, ', 'url': 'https://pubmed.ncbi.nlm.nih.gov/25051960/'}}
[ERROR] model invalid, please check the model engine selected!
```
我看了之前使用的codellma，似乎是有tokenizer.model等一些文件的，我查看一些相关的资料，现在tokenizer.model的存储形式似乎已经改为tokenizer_config.json，tokenizer.json等储存形式了，我不知道是否会对该些分析有所影响，不知道如何解决该问题

**Comment by JoshuaChou2018** [comment]
可以试试--model ollama_deepseek-coder-v2，独立部署local llm的方式会在未来版本中弃用

**Comment by wangnuo-log** [comment]
> 可以试试--model ollama_deepseek-coder-v2，独立部署local llm的方式会在未来版本中弃用

很感谢您的回答，我使用了deepseep-coder-v2结果也不是那么理想，但是我使用 ollama_qwen2.5-coder:32b 的时候，发现已经可以正常的使用其他的软件比对了，十分感谢

**Comment by MarilynWuu** [comment]
> Hi, invalid response是因为llm返回的结果不符合json格式，codellama-7bi模型性能比较差，建议使用34bi（可以使用ollama一键部署），或者使用GPT-4 API（目前测试效果最好）Hi, the "invalid response" is due to the LLM returning a result that doesn't conform to the JSON format. The Codellama-7bi model has relatively poor performance. It is recommended to use the 34bi model (which can be deployed with a single click via Ollama), or the GPT-4 API (which has shown the best test results so far).

请问这个问题可以通过修改提示词等解决吗，还是需要选择其他模型，我现在在使用deepseek-7bi时也遇到了这个问题一直无法解决
