### ISSUE TITLE
您好，请问A卡能安装吗

### ISSUE THREAD

**Issue by LIUDALILI** [JoshuaChou2018/AutoBA#14]
您好，我是刚开始接触生信，请问一下A卡能安装吗？能不能把安装过程说的再详细一点，我的基础比较薄弱，在用docker和自己配置服务器上很不擅长，不胜感激

**Comment by JoshuaChou2018** [comment]
hello我们没有测试过A卡，使用online llm的话不需要gpu

**Comment by LIUDALILI** [comment]
![微信图片_20241114172915](https://github.com/user-attachments/assets/d5d93fc1-6155-4c97-bdb0-74765c017f07)

请问这种情况怎么继续下去，我的代码基础比较薄弱

**Comment by LIUDALILI** [comment]
Can you please explain the installation process in more detail, I really have some trouble with the installation

**Comment by LIUDALILI** [comment]
您好，我应该怎样才能找到分析的结果，我用的是docker镜像



---原始邮件---
发件人: "Juexiao ***@***.***&gt;
发送时间: 2024年11月14日(周四) 下午5:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [JoshuaChou2018/AutoBA] 您好，请问A卡能安装吗 (Issue #14)




 
hello我们没有测试过A卡，使用online llm的话不需要gpu
