### ISSUE TITLE
Process killed when using codellama-7bi

### ISSUE THREAD

**Issue by AqibHasnain** [JoshuaChou2018/AutoBA#2]
I can run autoBA as instructed in the repo README if using gpt. however when I downloaded llama weights (`llama-7b-instruct`) I encounter the issue where after running `app.py` with `--model codellama-7bi` I get the following: 

`
>> start loading model
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Killed

`

I am using a fresh AWS-EC2 instance.

**Comment by JoshuaChou2018** [comment]
looks like OOM
