### ISSUE TITLE
Please help! Having trouble reproducing the result.

### ISSUE THREAD

**Issue by d5423197** [JoshuaChou2018/AutoBA#3]
Hello there,

Thanks for contributing such a great work to open community.

I tried case1.1 with openai gpt 3.5. 

I only get response in the first step which is the "plan phase", the agent successfully created a plan. 

But I failed in second step which is "code phase", the response message is empty.

Any response will be appreciated!

Best,

ZD

**Comment by JoshuaChou2018** [comment]
Hi, could you please share a screenshot?

**Comment by d5423197** [comment]
![1704877657556](https://github.com/JoshuaChou2018/AutoBA/assets/61330860/1fdeb2dc-1734-4006-9a19-56bba17397fe)

**Comment by JoshuaChou2018** [comment]
it looks like the problem of API, please pull our updated code and try to use with --model gpt-3.5-turbo-1106
