### ISSUE TITLE
Having trouble reproducing the result. The program is stuck at one step.

### ISSUE THREAD

**Issue by bamboosir920** [JoshuaChou2018/AutoBA#4]
When I ran example case1.1, I found that often at a step (especially with hisat2), the program would run forever, and at most, I tried to run it for 3 days without any changes. I found that the program process was still running, but neither memory nor CPU was being used. But since hisat2 has no feedback output, AutoBA will keep waiting for the result.

![image](https://github.com/JoshuaChou2018/AutoBA/assets/53424562/c7697a59-d9e7-4ae8-a93c-9bafc344c08f)

![image](https://github.com/JoshuaChou2018/AutoBA/assets/53424562/b35a63ec-0c5e-4ab3-99ea-e900cad3120d)

![image](https://github.com/JoshuaChou2018/AutoBA/assets/53424562/e1c94492-d3f4-486d-87a6-0469021fc28a)

**Comment by JoshuaChou2018** [comment]
Hi, which version did you use, main or dev-v3.3.0?

**Comment by JoshuaChou2018** [comment]
> Hi, which version did you use, main or dev-v3.3.0?

I just ran a demo on case1.1 and it works. According to your screenshot, hisat2 on SRR1374921 was finished (you have SRR1374921.sam), but it did not even start processing SRR1374922. Is it possible that your hisat2 is stuck at the backend? because hisat2 should give feedback to AutoBA when it finishes.

**Comment by JoshuaChou2018** [comment]
> > Hi, which version did you use, main or dev-v3.3.0?
> 
> I just ran a demo on case1.1 and it works. According to your screenshot, hisat2 on SRR1374921 was finished (you have SRR1374921.sam), but it did not even start processing SRR1374922. Is it possible that your hisat2 is stuck at the backend? because hisat2 should give feedback to AutoBA when it finishes.

![WX20240709-114559@2x](https://github.com/JoshuaChou2018/AutoBA/assets/25849209/09f73097-516c-41be-8a71-ae19974c3581)

**Comment by bamboosir920** [comment]
Ok, thank you. I'll try. I used main

**Comment by JoshuaChou2018** [comment]
dev-v0.3.0 has been merged into the main (was dev-v0.2.0) now. It is also suggested to prepare some small sample files to facilitate debugging.
